name: webenv
channels:
  - conda-forge
dependencies:
  - python=3.10.0

  # database
  - sqlalchemy
  - psycopg2

  # web
  - flask
  - requests

  # visualization
  - bokeh
  - matplotlib

  # numeric
  - pandas
  - numpy
  - scipy

  # test
  - pytest

  # formatting
  - black
  - flake8

  # packaging
  - pip

  - pip:
      - pyarrow
      - redis
