name: webenv
channels:
  - conda-forge
dependencies:
  - python=3.9.10

  # database
  - sqlalchemy
  - psycopg2

  # web
  - flask
  - requests

  # visualization
  - bokeh

  # numeric
  - pandas

  # formatting
  - black
  - flake8

  # packaging
  - pip

  - pip:
      - pyarrow
      - python-dotenv
      - redis
