version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-image
    restart: always
    entrypoint:
      - gunicorn
      - --bind=0.0.0.0:5000
      - --workers=3
      - app:app
    ports:
      - target: 5000
        published: 5000
    volumes:
      - .:/website

  postgres:
    image: postgres:10
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    depends_on:
      - postgres
    volumes:
      - redisdata:/data

  services:
    image: web-image
    restart: always
    depends_on:
      - redis
    entrypoint:
      - sh
      - scripts/services.sh
    volumes:
      - .:/website

  bokeh:
    image: web-image
    restart: always
    depends_on:
      - redis
    entrypoint:
      - bokeh
      - serve
      - projects/electability-in-2020/
      - --port=5006
      - --prefix=/plot
      - --use-xheaders
      - --allow-websocket-origin=www.joshvieira.com
      - --allow-websocket-origin=localhost:5006
    ports:
      - target: 5006
        published: 5006
    volumes:
      - .:/website

volumes:
  pgdata:
  redisdata:
