version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-image
    entrypoint:
      - python
      - app/website.py
    ports:
      - target: 5000
        published: 5000
    volumes:
      - .:/website

  postgres:
    image: postgres:10
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - target: 5432
        published: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    depends_on:
      - postgres
    ports:
     - target: 6379
       published: 6379
    volumes:
      - redisdata:/data

  services:
    image: web-image
    depends_on:
      - redis
    entrypoint:
      - sh
      - scripts/services.sh
    volumes:
      - .:/website

  bokeh:
    image: web-image
    depends_on:
      - redis
    entrypoint:
      - bokeh
      - serve
      - projects/electability-in-2020/
      - --port=5006
    ports:
      - target: 5006
        published: 5006
    volumes:
      - .:/website

volumes:
  pgdata:
  redisdata:
